openapi: 3.0.0
info:
  title: Card Detail API
  description: API para obtener el detalle de una tarjeta bancaria
  version: 1.0.0

paths:
  /cards/{cardId}:
    get:
      summary: Obtener detalle de tarjeta
      description: Recupera la información detallada de una tarjeta bancaria
      parameters:
        - name: cardId
          in: path
          required: true
          description: Identificador único de la tarjeta
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardDetail'
        '404':
          description: Tarjeta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CardDetail:
      type: object
      properties:
        cardId:
          type: string
          description: Identificador único de la tarjeta
        cardNumber:
          type: string
          description: Número completo o enmascarado de la tarjeta
        cardType:
          type: string
          enum: [DEBIT, CREDIT, PREPAID, BUSINESS]
          description: Tipo de tarjeta
        status:
          type: string
          enum: [ACTIVE, INACTIVE, BLOCKED, EXPIRED]
          description: Estado actual de la tarjeta
        holder:
          type: object
          properties:
            name:
              type: string
              description: Nombre del titular
            customerId:
              type: string
              description: ID del titular
        expirationDate:
          type: string
          pattern: '^[0-9]{4}-[0-9]{2}$'
          description: Fecha de expiración (YYYY-MM)
        imageCode:
          type: string
          description: Código de imagen para mostrar la tarjeta
        lastUpdated:
          type: string
          format: date-time
          description: Última actualización
        panReference:
          type: string
          description: Referencia interna del PAN/token
        issuer:
          type: string
          description: Nombre del emisor de la tarjeta
        network:
          type: string
          description: Red de la tarjeta (ej: VISA, MASTERCARD)
        limits:
          type: object
          properties:
            dailyLimit:
              type: number
              format: double
              description: Límite diario de gasto
            monthlyLimit:
              type: number
              format: double
              description: Límite mensual de gasto
            currency:
              type: string
              description: Moneda de los límites
      required:
        - cardId
        - cardNumber
        - cardType
        - status
        - holder
        - expirationDate
        - imageCode
        - lastUpdated
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
