openapi: 3.0.0
info:
  title: Global Position API
  description: API to retrieve the user's global financial position (accounts and cards)
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /global-position:
    get:
      summary: Get global position
      description: Returns all accounts and cards for the user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      $ref: '#/components/schemas/AccountMinimal'
                  cards:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardMinimal'
                required:
                  - accounts
                  - cards

  schemas:
    AccountMinimal:
      type: object
      properties:
        accountId:
          type: string
        accountType:
          type: string
        status:
          type: string
        balance:
          type: object
          properties:
            available:
              type: number
            currency:
              type: string
        imageCode:
          type: string
      required:
        - accountId
        - accountType
        - status
        - balance
        - imageCode
    CardMinimal:
      type: object
      properties:
        cardId:
          type: string
        cardType:
          type: string
        status:
          type: string
        imageCode:
          type: string
      required:
        - cardId
        - cardType
        - status
        - imageCode
