openapi: 3.0.0
info:
  title: Data Encryption Service API
  description: API to encrypt data using a private key identified by alias
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /encrypt:
    post:
      summary: Encrypt data
      description: Encrypts a value using the private key associated with the provided alias and algorithm. Requires Bearer JWT authentication.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                alias:
                  type: string
                  description: Alias to identify the private key
                algorithm:
                  type: string
                  description: Encryption algorithm (e.g., RSA, AES)
                value:
                  type: string
                  description: Value to be encrypted
              required:
                - alias
                - algorithm
                - value
      responses:
        '200':
          description: Data encrypted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  encrypted:
                    type: string
                    description: Encrypted value (base64 or hex encoded)
                required:
                  - encrypted
        '401':
          description: Invalid or expired token
        '404':
          description: Alias not found
        '400':
          description: Invalid request
