openapi: 3.0.0
info:
  title: User Contact Data API
  description: API to retrieve full user personal and contact data
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /user/contact:
    get:
      summary: Get full user personal and contact data
      description: Returns the user's complete personal and contact information. Requires Bearer JWT authentication.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserContact'
        '401':
          description: Invalid or expired token

components:
  schemas:
    UserContact:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        address:
          type: string
        birthDate:
          type: string
          format: date
        birthPlace:
          type: string
        nationality:
          type: string
        documentType:
          type: string
        documentNumber:
          type: string
        gender:
          type: string
        maritalStatus:
          type: string
        spouseName:
          type: string
        children:
          type: integer
        occupation:
          type: string
        employer:
          type: string
        educationLevel:
          type: string
        fieldOfStudy:
          type: string
        graduationYear:
          type: string
        languages:
          type: array
          items:
            type: string
        incomeLevel:
          type: string
        housingType:
          type: string
        residenceStatus:
          type: string
      required:
        - userId
        - name
        - firstName
        - lastName
        - email
        - phone
        - address
        - birthDate
        - birthPlace
        - nationality
        - documentType
        - documentNumber
        - gender
        - maritalStatus
        - occupation
        - educationLevel
        - languages
        - incomeLevel
        - housingType
        - residenceStatus
